# file: .github/dependabot.yml
# (c) 2025 Asymmetric Effort, LLC. scaldwell@asymmetric-effort.com
# Dependabot configuration for keeping dependencies up to date.

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
