version: '3'
tasks:
  bootstrap:
    cmds:
      - go mod tidy
      - go list ./...
  unit:
    cmds:
      - go vet ./...
      - staticcheck ./...
      - go test ./... -short -cover
  integration:
    cmds:
      - go test ./... -run Integration -covermode=atomic -coverpkg=./... -coverprofile=coverage.out
      - go tool cover -func=coverage.out | awk '/total:/ { print; if ($3+0 < 80) exit 1 }'
  build:
    cmds:
      - go build -trimpath -ldflags "-s -w" ./cmd/docker-lint
  all:
    deps: [bootstrap, unit, integration, build]