# file: .github/workflows/ci.yml
# (c) 2025 Asymmetric Effort, LLC. scaldwell@asymmetric-effort.com
name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod tidy
      - name: Check formatting
        run: test -z "$(gofmt -l .)"
      - name: Vet
        run: go vet ./...
      - name: Unit tests
        run: go test ./... -short -cover
      - name: Integration tests
        run: |
          go test ./... -run Integration -covermode=atomic -coverpkg=./... -coverprofile=coverage.out
          go tool cover -func=coverage.out | awk '/total:/ { print; if ($3+0 < 80) exit 1 }'
      - name: Build
        run: go build -trimpath -ldflags "-s -w" ./cmd/docker-lint

