# file: .github/workflows/ci.yml
# (c) 2025 Asymmetric Effort, LLC. scaldwell@asymmetric-effort.com
name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Install dependencies
        run: go mod tidy
      - name: Check formatting
        run: test -z "$(gofmt -l .)"
      - name: Lint
        run: |
          go vet ./...
          command -v staticcheck || go install honnef.co/go/tools/cmd/staticcheck@latest
          staticcheck ./...
      - name: Unit tests
        run: go test ./... -short -cover
      - name: Integration tests
        run: |
          go test ./... -run Integration -covermode=atomic -coverpkg=./... -coverprofile=coverage.out
          go tool cover -func=coverage.out | awk '/total:/ { print; if ($3+0 < 80) exit 1 }'

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, arm64be]
        exclude:
          - goos: windows
            goarch: arm64be
          - goos: darwin
            goarch: arm64be
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Build
        run: |
          if go tool dist list | grep -q "${{ matrix.goos }}/${{ matrix.goarch }}"; then
            GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags "-s -w" -o build/${{ matrix.goos }}_${{ matrix.goarch }}/docker-lint ./cmd/docker-lint
          else
            echo "Skipping unsupported platform ${{ matrix.goos }}/${{ matrix.goarch }}"
          fi
      - name: Upload artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-lint-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/${{ matrix.goos }}_${{ matrix.goarch }}/docker-lint

